### ISSUE TITLE
mock配置中的方法执行错误，导致 vite开发服务终止

### ISSUE THREAD

**Issue by pengzhanbo** [pengzhanbo/vite-plugin-mock-dev-server#17]
_Originally posted by @kenixFog in https://github.com/pengzhanbo/vite-plugin-mock-dev-server/issues/15#issuecomment-1445613027_

> 遇到个新"问题"，但是不晓得能不能从插件层面进行容错~~
>
>```
>body: (res, query, params, body) => {   ❌
>```
>
>这个修改的时候，我改错了，我写成了
>
>```
>(body: (res,  {query, params, body} ) => {)
>```
>
>然后导致程序直接退出
>```
>
> E:\0WorkSpace\app\mock\api.mock.ts:30
>    body: (res, { query, params, body }) => {
>                  ^
>
>TypeError: Cannot destructure property 'query' of 'undefined' as it is undefined.
>    at Object.body (E:\0WorkSpace\app\mock\api.mock.ts:30:19)
>    at E:\0WorkSpace\app\node_modules\.pnpm\vite-plugin-mock-dev-server@0.4.2_vite@4.1.4\node_modules\vite-plugin->mock-dev-server\dist\index.cjs:456:34
>    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>
>Node.js v19.6.0
>ELIFECYCLE  Command failed with exit code 1.
>```
>
>这个写法肯定有问题，但万一手抖，改错了。。重新启动，时间成本略微有点高~
>

**Comment by pengzhanbo** [comment]
@kenixFog 这个是可以在插件内进行处理的，我会在下个小版本中处理这种情况。

**Comment by pengzhanbo** [comment]
@kenixFog `v0.4.3` 版本已修复该问题。
