### ISSUE TITLE
mock文件夹下的空文件会导致异常

### ISSUE THREAD

**Issue by kenixFog** [pengzhanbo/vite-plugin-mock-dev-server#19]
vite正常运行，在mock下创建.ts空文件，会导致vite异常终止，或者mock下存在空的ts文件，vite无法启动

```
node:internal/errors:490
    ErrorCaptureStackTrace(err);
    ^

TypeError: The "url" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:399:5)
    at validateString (node:internal/validators:163:11)
    at Url.parse (node:url:175:3)
    at urlParse (node:url:146:13)
    at E:\0WorkSpace\VsCode\xianhuo\dlsc-app-naiveUI\node_modules\.pnpm\vite-plugin-mock-dev-server@1.0.2_vite@4.1.4\node_modules\vite-plugin-mock-dev-server\dist\index.cjs:645:62
    at Array.forEach (<anonymous>)
    at _MockLoader.updateMockList (E:\0WorkSpace\VsCode\xianhuo\dlsc-app-naiveUI\node_modules\.pnpm\vite-plugin-mock-dev-server@1.0.2_vite@4.1.4\node_modules\vite-plugin-mock-dev-server\dist\index.cjs:644:84)
    at _MockLoader.<anonymous> (E:\0WorkSpace\VsCode\xianhuo\dlsc-app-naiveUI\node_modules\.pnpm\vite-plugin-mock-dev-server@1.0.2_vite@4.1.4\node_modules\vite-plugin-mock-dev-server\dist\index.cjs:567:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by pengzhanbo** [comment]
该问题已在 `v1.0.3` 中修复
