### ISSUE TITLE
mockServer 独立部署安装和启动报错

### ISSUE THREAD

**Issue by U-Wen** [pengzhanbo/vite-plugin-mock-dev-server#63]
## 安装报错
``` bash
yarn install v1.22.19
warning package.json: No license field
warning mock-server: No license field
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.npmmirror.com/@%2ftypes: [NOT_FOUND] /@%2ftypes not found".
info If you think this is a bug, please open a bug report with the information provided in "D:\\MyProject\\nanke-web\\dist\\mockServer\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
查询原因是 `package.json` 中的依赖 `"@/types": "latest"` 导致的。将之删除后，进行 `yarn start`，出现启动报错

## 启动报错
``` bash
$ node index.js
file:///D:/MyProject/nanke-web/dist/mockServer/node_modules/vite-plugin-mock-dev-server/dist/index.js:1329
  (_a = loader.on) == null ? void 0 : _a.call(loader, "mock:update-end", (filepath) => {
               ^

TypeError: Cannot read properties of undefined (reading 'on')
    at mockWebSocket (file:///D:/MyProject/nanke-web/dist/mockServer/node_modules/vite-plugin-mock-dev-server/dist/index.js:1329:16)
    at file:///D:/MyProject/nanke-web/dist/mockServer/index.js:14:1
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

@pengzhanbo

**Comment by U-Wen** [comment]
node 版本 `v16.20.1`
npm 版本 `8.19.4`
yarn 版本 `v1.22.19`

**Comment by U-Wen** [comment]
插件版本 `vite-plugin-mock-dev-server@1.3.4`

**Comment by pengzhanbo** [comment]
该问题已修复，并发布于  `v1.4.1`。
