### ISSUE TITLE
请求体过大报错

### ISSUE THREAD

**Issue by RockyF** [pengzhanbo/vite-plugin-mock-dev-server#76]
### Bug 描述

如题，在请求时传了个很大的body后，`raw-body`解析`request`时报
`PayloadTooLargeError: request entity too large`
因为`co-body`默认的`limit`为`1mb`，建议在传入一个很大的`limit`配置，具体数值看你掐指一算

### 系统环境

```markdown
- OS: macOS 13.6.5
- Node: 18
- packageManager: yarn
- vite: ^4.4.5
- vite-plugin-mock-dev-server: ^1.4.7
```

### Logs

PayloadTooLargeError: request entity too large
at readStream (node_modules/raw-body/index.js:163:17)
at executor (node_modules/raw-body/index.js:120:5)
at new Promise (<anonymous>)
  at getRawBody (node_modules/raw-body/index.js:119:10)
  at module.exports [as json] (node_modules/co-body/lib/json.js:39:21)
  at parseReqBody (file://node_modules/vite-plugin-mock-dev-server/dist/index.js:656:31)
  at file://node_modules/vite-plugin-mock-dev-server/dist/index.js:775:27
  at call (file://node_modules/vite/dist/node/chunks/dep-52909643.js:50689:7)
  at next (file://node_modules/vite/dist/node/chunks/dep-52909643.js:50633:5)
  at cors (node_modules/cors/lib/index.js:188:7)
  at node_modules/cors/lib/index.js:224:17
  at originCallback (node_modules/cors/lib/index.js:214:15)
  at node_modules/cors/lib/index.js:219:13
  at optionsCallback (node_modules/cors/lib/index.js:199:9)
  at corsMiddleware (node_modules/cors/lib/index.js:204:7)
  at file://node_modules/vite-plugin-mock-dev-server/dist/index.js:1534:22
  at call (file://node_modules/vite/dist/node/chunks/dep-52909643.js:50689:7)
  at next (file://node_modules/vite/dist/node/chunks/dep-52909643.js:50633:5)
  at Function.handle (file://node_modules/vite/dist/node/chunks/dep-52909643.js:50636:3)
  at Server.app (file://node_modules/vite/dist/node/chunks/dep-52909643.js:50501:37)
  at Server.emit (node:events:517:28)
  at parserOnIncoming (node:_http_server:1123:12)
  at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17) {
    expected: 2003701,
    length: 2003701,
    limit: 1048576,
    type: 'entity.too.large'
  }

**Comment by pengzhanbo** [comment]
针对请求体大小的限制，我在 插件配置中新增了 `bodyParserOptions` 选项，你可以根据自己的需求场景，自行设置限制大小。

```ts
plugins: [
  mockDevServerPlugin({
    bodyParserOptions: {
      limit: '2mb', // 通用选项
      jsonLimit: '2mb', // 指定 json 类型的请求体大小限制为 2mb
      formLimit: '',
      textLimit: '',
    }
  }),
],
```
